name: Backend & Infrastructure Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'backend/**'
      - 'infra/**'
      - 'package.json'
      - '.github/workflows/backend-infra-deploy.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '18'
  ECR_REGISTRY: ${{ secrets.AWS_ECR_REGISTRY }}
  ECR_REPOSITORY: clubapp-backend
  TERRAFORM_VERSION: '1.13.4'

jobs:
  build-backend:
    name: Build Backend Docker Image
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    outputs:
      image-uri: ${{ steps.image.outputs.uri }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "tag=latest-prod" >> $GITHUB_OUTPUT
          else
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "tag=latest-staging" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: |
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}
            ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ steps.env.outputs.tag }}
          cache-from: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:buildcache
          cache-to: type=registry,ref=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:buildcache,mode=max

      - name: Output image URI
        id: image
        run: |
          IMAGE_URI="${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}"
          echo "uri=${IMAGE_URI}" >> $GITHUB_OUTPUT
          echo "Docker image built: ${IMAGE_URI}"

  deploy-infrastructure:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Terraform Format Check
        id: fmt
        run: terraform fmt -check -recursive ./infra/terraform
        continue-on-error: true

      - name: Terraform Init
        id: init
        run: |
          cd infra/terraform
          terraform init \
            -backend-config="bucket=clubapp-terraform-state" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="region=${{ env.AWS_REGION }}"

      - name: Terraform Validate
        id: validate
        run: |
          cd infra/terraform
          terraform validate -json

      - name: Terraform Plan
        id: plan
        run: |
          cd infra/terraform
          terraform plan \
            -var-file=terraform.tfvars \
            -json > plan.json || true
        continue-on-error: true

      - name: Terraform Apply
        id: apply
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra/terraform
          
          # Get the existing lock ID from DynamoDB and force unlock it
          # The lock appears to be stuck, so we need to remove it directly
          LOCK_ID="609fc745-68f1-7cea-6fbe-7389c8954b8a"
          
          # Try to delete the lock from DynamoDB using AWS CLI
          echo "Attempting to clear stuck Terraform state lock..."
          aws dynamodb delete-item \
            --table-name clubapp-terraform-state \
            --key "{\"LockID\":{\"S\":\"clubapp-terraform-state/terraform.tfstate\"}}" \
            --region us-east-1 \
            2>/dev/null || echo "No lock found in DynamoDB (expected if already cleared)"
          
          # Alternative: Use Terraform force-unlock with the known lock ID
          if [ ! -z "$LOCK_ID" ]; then
            echo "Forcing unlock of stuck lock: $LOCK_ID"
            terraform force-unlock -force "$LOCK_ID" 2>/dev/null || echo "Could not force unlock (continuing anyway)"
          fi
          
          # Wait a moment for lock to be released
          sleep 2
          
          # IMPORTANT: Refresh state to sync with actual AWS resources
          # This prevents "resource already exists" errors when Terraform state is out of sync
          echo "Refreshing Terraform state to match actual AWS resources..."
          terraform refresh \
            -var-file=terraform.tfvars \
            -lock=true || echo "State refresh completed with warnings"
          
          # Wait before applying
          sleep 2
          
          # Now apply with full logging
          echo "Proceeding with Terraform apply..."
          terraform apply \
            -var-file=terraform.tfvars \
            -auto-approve \
            -input=false \
            -lock=true
        env:
          TF_LOG: INFO

      - name: Get Terraform Outputs
        id: outputs
        if: github.ref == 'refs/heads/main'
        run: |
          cd infra/terraform
          terraform output -json > outputs.json
          cat outputs.json

      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = JSON.parse(fs.readFileSync('./infra/terraform/plan.json', 'utf8'));
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Terraform Plan\n\`\`\`json\n${JSON.stringify(plan, null, 2)}\n\`\`\``
            });

  deploy-backend:
    name: Deploy Backend to ECS
    needs: [build-backend, deploy-infrastructure]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}
          audience: sts.amazonaws.com

      - name: Determine environment
        id: env
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "cluster=clubapp-prod" >> $GITHUB_OUTPUT
            echo "service=clubapp-backend-prod" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "cluster=clubapp-dev" >> $GITHUB_OUTPUT
            echo "service=clubapp-backend" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Update ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ./backend/task-definition.json
          container-name: ${{ env.ECR_REPOSITORY }}
          image: ${{ needs.build-backend.outputs.image-uri }}

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ steps.env.outputs.service }}
          cluster: ${{ steps.env.outputs.cluster }}
          wait-for-service-stability: true

      - name: Check service health
        run: |
          for i in {1..30}; do
            DESIRED=$(aws ecs describe-services \
              --cluster ${{ steps.env.outputs.cluster }} \
              --services ${{ steps.env.outputs.service }} \
              --query 'services[0].desiredCount' \
              --output text)
            RUNNING=$(aws ecs describe-services \
              --cluster ${{ steps.env.outputs.cluster }} \
              --services ${{ steps.env.outputs.service }} \
              --query 'services[0].runningCount' \
              --output text)
            
            if [ "$DESIRED" -eq "$RUNNING" ]; then
              echo "✅ All tasks are running"
              exit 0
            fi
            
            echo "Waiting... ($i/30) - Desired: $DESIRED, Running: $RUNNING"
            sleep 10
          done
          
          echo "❌ Service did not reach desired state"
          exit 1

      - name: Deployment Summary
        run: |
          echo "✅ Backend deployment complete"
          echo "Environment: ${{ steps.env.outputs.environment }}"
          echo "Image URI: ${{ needs.build-backend.outputs.image-uri }}"
