name: Frontend Deploy

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'src/**'
      - 'package.json'
      - 'vite.config.ts'
      - '.github/workflows/frontend-deploy.yml'
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  NODE_VERSION: '18'

jobs:
  build-and-deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build production bundle
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Determine S3 bucket
        id: bucket
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "bucket=${{ secrets.AWS_S3_PRODUCTION_BUCKET }}" >> $GITHUB_OUTPUT
            echo "distribution=${{ secrets.AWS_CLOUDFRONT_PRODUCTION_ID }}" >> $GITHUB_OUTPUT
            echo "environment=production" >> $GITHUB_OUTPUT
          else
            echo "bucket=${{ secrets.AWS_S3_STAGING_BUCKET }}" >> $GITHUB_OUTPUT
            echo "distribution=${{ secrets.AWS_CLOUDFRONT_STAGING_ID }}" >> $GITHUB_OUTPUT
            echo "environment=staging" >> $GITHUB_OUTPUT
          fi

      - name: Upload to S3
        run: |
          aws s3 sync dist/ s3://${{ steps.bucket.outputs.bucket }}/ \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "index.html"
          
          aws s3 cp dist/index.html s3://${{ steps.bucket.outputs.bucket }}/index.html \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate" \
            --content-type "text/html"

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ steps.bucket.outputs.distribution }} \
            --paths "/*"

      - name: Slack notification (Success)
        if: success()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          payload: |
            {
              "text": "Frontend deployment successful",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "✅ Frontend deployed to *${{ steps.bucket.outputs.environment }}*\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}`"
                  }
                }
              ]
            }

      - name: Slack notification (Failure)
        if: failure()
        uses: slackapi/slack-github-action@v1.24.0
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK }}
          payload: |
            {
              "text": "Frontend deployment failed",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "❌ Frontend deployment failed\nBranch: `${{ github.ref_name }}`\nCommit: `${{ github.sha }}`"
                  }
                }
              ]
            }
